### PR TITLE
resolves #10: Supporting custom functions

### LINKED ISSUE #10: Add support for user-defined functions
From the discussion on fortran-lang discourse : https://fortran-lang.discourse.group/t/feq-parse-updates-evaluation-with-arrays-now-supported/6871/7

> Another thought I had was, which methods of the equation parser (if any) are overriddable, and would this make it possible to implement custom operators?

### PR DESCRIPTION
**Pull request by davidpfister**
Hi @fluidnumerics-joe, 
I had a bit of time so I added the possibility to create custom functions (I have seen it in your to-do list). I used functions pointers for this and so I had to change the way the functions are parsed and evaluated. I think it is even more efficient now, because the `if` statements from the f_of_x function are not necessary anymore.

**Changes**
- Addition of TokenId in to keep track of the index of the parsed function in the `Functions` array
- Addition of procedure pointers in the Function derived type. The procedure HAVE to be pure
- Slight change in the `IsFunction` function that detect directly if the trailing `(` is present.
- Addition of 2 test cases: 1 for parsing complex expressions and 1 for custom functions.

### CODE REVIEW

**Comment by fluidnumerics-joe** [comment]
@davidpfister - I'll get this on the wheel to take a look at. It looks like there are some issues with the ifort/ifx builds that we'll need to straighten out. I'll also take a look at codecov to see what lines of code are not being exercised here.

**Comment by davidpfister** [comment]
I have seen the issues with intel, but I am not sure to get the problem. It works fine on Windows when compiled with VS2019. I also used -check:all to see if I missed something, but there was no warning. 
Let me know if I can do anything. 
Still one thing: the make files are not up to date and do not include the last tests.

**Comment by fluidnumerics-joe** [comment]
> I have seen the issues with intel, but I am not sure to get the problem. It works fine on Windows when compiled with VS2019. I also used -check:all to see if I missed something, but there was no warning. Let me know if I can do anything. Still one thing: the make files are not up to date and do not include the last tests.

You've done quite a bit here and it looks great. I'm going to try out your branch and see if I can dump more information than what the CI is showing (SEGFAULT on all the tests run with ctest with the Intel builds on Linux). I'll get back to you with some actionable information soon..

**Comment by fluidnumerics-joe** [comment]
Here's what valgrind shows with ifort on ubuntu 22.04

```
$ valgrind ./testsuite abs_r1fp32_
==28418== Memcheck, a memory error detector
==28418== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==28418== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==28418== Command: ./testsuite abs_r1fp32_
==28418== 
==28418== Jump to the invalid address stated on the next line
==28418==    at 0x0: ???
==28418==    by 0x48F175B: for__issue_diagnostic (in /home/joe/.software/spack/opt/spack/linux-pop22-skylake/gcc-11.3.0/intel-oneapi-compilers-2023.2.1-zb2owmphmm6dymlnh7drj7ueetxsvtia/compiler/2023.2.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5)
==28418==    by 0x48F2C38: for_emit_diagnostic (in /home/joe/.software/spack/opt/spack/linux-pop22-skylake/gcc-11.3.0/intel-oneapi-compilers-2023.2.1-zb2owmphmm6dymlnh7drj7ueetxsvtia/compiler/2023.2.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5)
==28418==    by 0x758D66: feqparse_functions_mp_initializefunctions_ (FEQParse_Functions.F90:167)
==28418==    by 0x6DA428: feqparse_mp_construct_equationparser_ (FEQParse.F90:100)
==28418==    by 0x415933: abs_r1fp32_ (abs_r1fp32.f90:22)
==28418==    by 0x414E5E: main (main.c:1021)
==28418==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==28418== 
==28418== 
==28418== Process terminating with default action of signal 11 (SIGSEGV)
==28418==  Bad permissions for mapped region at address 0x0
==28418==    at 0x0: ???
==28418==    by 0x48F175B: for__issue_diagnostic (in /home/joe/.software/spack/opt/spack/linux-pop22-skylake/gcc-11.3.0/intel-oneapi-compilers-2023.2.1-zb2owmphmm6dymlnh7drj7ueetxsvtia/compiler/2023.2.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5)
==28418==    by 0x48F2C38: for_emit_diagnostic (in /home/joe/.software/spack/opt/spack/linux-pop22-skylake/gcc-11.3.0/intel-oneapi-compilers-2023.2.1-zb2owmphmm6dymlnh7drj7ueetxsvtia/compiler/2023.2.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5)
==28418==    by 0x758D66: feqparse_functions_mp_initializefunctions_ (FEQParse_Functions.F90:167)
==28418==    by 0x6DA428: feqparse_mp_construct_equationparser_ (FEQParse.F90:100)
==28418==    by 0x415933: abs_r1fp32_ (abs_r1fp32.f90:22)
==28418==    by 0x414E5E: main (main.c:1021)
==28418== 
==28418== HEAP SUMMARY:
==28418==     in use at exit: 26,882 bytes in 11 blocks
==28418==   total heap usage: 16 allocs, 5 frees, 31,578 bytes allocated
==28418== 
==28418== LEAK SUMMARY:
==28418==    definitely lost: 0 bytes in 0 blocks
==28418==    indirectly lost: 0 bytes in 0 blocks
==28418==      possibly lost: 2,080 bytes in 1 blocks
==28418==    still reachable: 24,802 bytes in 10 blocks
==28418==         suppressed: 0 bytes in 0 blocks
==28418== Rerun with --leak-check=full to see details of leaked memory
==28418== 
==28418== For lists of detected and suppressed errors, rerun with: -s
==28418== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

It seems to be associated with the function initialization, but it's not clear why Intel fails this on Linux and not windows..

**Comment by fluidnumerics-joe** [comment]
Also, parsing and evaluation is faster :-1:  
I'll pull profile/timing for comparison next week.

**Comment by davidpfister** [comment]
I ran intel inspector and noticed that the character array assignment was making strange things. I introduced a tuple rather than an array, and inspector does not complain anymore. 
Seems like it improved something but fpm+ifort is still failing.

**Comment by fluidnumerics-joe** [comment]
Looks like fpm build is failing for different reasons though, which is good. The CMake build now works for  ifort and ifx

**Comment by fluidnumerics-joe** [comment]
This looks like a similar error. 
```
valgrind ./custom-tests 
==37991== Memcheck, a memory error detector
==37991== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==37991== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==37991== Command: ./custom-tests
==37991== 
==37991== Warning: ignored attempt to set SIGKILL handler in sigaction();
==37991==          the SIGKILL signal is uncatchable
==37991== Warning: ignored attempt to set SIGSTOP handler in sigaction();
==37991==          the SIGSTOP signal is uncatchable
==37991== Warning: ignored attempt to set SIGRT32 handler in sigaction();
==37991==          the SIGRT32 signal is used internally by Valgrind
forrtl: severe (122): invalid attempt to assign into a pointer that is not associated
Image              PC                Routine            Line        Source             
custom-tests       000000000049876F  Unknown               Unknown  Unknown
custom-tests       0000000000412AFD  feqparse_function         278  FEQParse_Functions.F90
custom-tests       0000000000404A99  test_IP_testing_           18  test.f90
custom-tests       000000000040429E  MAIN__                      8  test.f90
custom-tests       00000000004041CD  Unknown               Unknown  Unknown
libc.so.6          000000000498DD90  Unknown               Unknown  Unknown
libc.so.6          000000000498DE40  __libc_start_main     Unknown  Unknown
custom-tests       00000000004040E5  Unknown               Unknown  Unknown
```
The line in question is [278 in FEQParse_Functions.F90](https://github.com/davidpfister/feq-parse/blob/master/src/FEQParse_Functions.F90#L278) . Seems to be something off with allocate on assignment with ifort/ifx on linux..

Originally, when I was thinking about this issue, I was considering using a linked list for the list of functions. The benefit of your approach though is immediately having the index for the function in question.

**Comment by fluidnumerics-joe** [comment]
I'm leaning towards accepting this PR to get this merged in. 

I'll take care of getting these new tests into the CMake build system too. Currently, the Intel tests pass with CMake b/c the custom tests are not included in the `ctest` test suite. It's also why the coverage is a bit lower. I'll open up a bug issue on this in this repo and see if we can come up with a  minimal reproducer to engage the broader fortran community on.

**Pull request merged**
